port: 7890
socks-port: 7891
allow-lan: true
mode: Rule
log-level: info
external-controller: :9090
proxies:
  - {name: 香港_BGP中继_01, server: 120.232.153.40, port: 36609, type: vmess, uuid: 418048af-a293-4b99-9b0c-98ca3580dd24, alterId: 64, cipher: auto, tls: false}
  - {name: 香港_IEPL专线_02, server: hk.example.com, port: 80, type: vmess, uuid: 47e91fb6-25b8-df52-bc18-3cdc8548192f, alterId: 2, cipher: auto, tls: false, network: ws, ws-opts: {path: /, headers: {Host: hk.example.com}}}
  - {name: 香港_腾讯云专线_03, server: 120.232.153.63, port: 37805, type: vmess, uuid: 418048af-a293-4b99-9b0c-98ca3580dd24, alterId: 0, cipher: auto, tls: false}
  - {name: 美国_洛杉矶_01, server: us.example.com, port: 443, type: trojan, password: cd41b9d7-df15-46ad-a778-257b0851525a, sni: us.example.com, skip-cert-verify: true}
  - {name: 新加坡_01, server: sg.example.com, port: 443, type: trojan, password: password123, sni: sg.example.com, skip-cert-verify: true}
  - {name: 日本_东京_01, server: jp.example.com, port: 28503, type: ss, cipher: chacha20-ietf-poly1305, password: password123}
  - {name: 台湾_01, server: tw.example.com, port: 8388, type: ss, cipher: chacha20-ietf, password: password123}
  - {name: 韩国_01, server: kr.example.com, port: 15003, type: ss, cipher: aes-256-gcm, password: password123}
proxy-groups:
  - name: 🚀 节点选择
    type: select
    proxies:
      - ♻️ 自动选择
      - DIRECT
      - 香港_BGP中继_01
      - 香港_IEPL专线_02
      - 香港_腾讯云专线_03
      - 美国_洛杉矶_01
      - 新加坡_01
      - 日本_东京_01
      - 台湾_01
      - 韩国_01
  - name: ♻️ 自动选择
    type: url-test
    url: http://www.gstatic.com/generate_204
    interval: 300
    tolerance: 50
    proxies:
      - 香港_BGP中继_01
      - 香港_IEPL专线_02
      - 香港_腾讯云专线_03
      - 美国_洛杉矶_01
      - 新加坡_01
      - 日本_东京_01
      - 台湾_01
      - 韩国_01
  - name: 🌍 国外媒体
    type: select
    proxies:
      - 🚀 节点选择
      - ♻️ 自动选择
      - 🇭🇰 香港节点
      - 🇨🇳 台湾节点
      - 🇸🇬 狮城节点
      - 🇯🇵 日本节点
      - 🇺🇸 美国节点
      - 🇰🇷 韩国节点
      - DIRECT
  - name: 📲 电报信息
    type: select
    proxies:
      - 🚀 节点选择
      - 🇸🇬 狮城节点
      - 🇭🇰 香港节点
      - 🇨🇳 台湾节点
      - 🇯🇵 日本节点
      - 🇺🇸 美国节点
      - 🇰🇷 韩国节点
      - DIRECT
  - name: Ⓜ️ 微软服务
    type: select
    proxies:
      - DIRECT
      - 🚀 节点选择
      - 🇭🇰 香港节点
      - 🇨🇳 台湾节点
      - 🇸🇬 狮城节点
      - 🇯🇵 日本节点
      - 🇺🇸 美国节点
      - 🇰🇷 韩国节点
  - name: 🍎 苹果服务
    type: select
    proxies:
      - DIRECT
      - 🚀 节点选择
      - 🇭🇰 香港节点
      - 🇨🇳 台湾节点
      - 🇸🇬 狮城节点
      - 🇯🇵 日本节点
      - 🇺🇸 美国节点
      - 🇰🇷 韩国节点
  - name: 🇭🇰 香港节点
    type: select
    proxies:
      - 香港_BGP中继_01
      - 香港_IEPL专线_02
      - 香港_腾讯云专线_03
  - name: 🇨🇳 台湾节点
    type: select
    proxies:
      - 台湾_01
  - name: 🇸🇬 狮城节点
    type: select
    proxies:
      - 新加坡_01
  - name: 🇯🇵 日本节点
    type: select
    proxies:
      - 日本_东京_01
  - name: 🇺🇸 美国节点
    type: select
    proxies:
      - 美国_洛杉矶_01
  - name: 🇰🇷 韩国节点
    type: select
    proxies:
      - 韩国_01
rules:
  - DOMAIN-SUFFIX,google.com,🚀 节点选择
  - DOMAIN-SUFFIX,youtube.com,🚀 节点选择
  - DOMAIN-SUFFIX,facebook.com,🚀 节点选择
  - DOMAIN-SUFFIX,twitter.com,🚀 节点选择
  - DOMAIN-SUFFIX,instagram.com,🚀 节点选择
  - DOMAIN-SUFFIX,netflix.com,🌍 国外媒体
  - DOMAIN-SUFFIX,telegram.org,📲 电报信息
  - DOMAIN-SUFFIX,microsoft.com,Ⓜ️ 微软服务
  - DOMAIN-SUFFIX,apple.com,🍎 苹果服务
  - DOMAIN-SUFFIX,cn,DIRECT
  - GEOIP,CN,DIRECT
  - MATCH,🚀 节点选择 